trigger:
- test

pool:
  name: 'demovmpool'

variables:
  resourceGroupName: 'demoRG1'
  location: 'UKSouth'
  deploymentName: 'demovm-deployment'

steps:
- script: |
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    az --version
  displayName: 'Install Azure CLI'
# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'Pay-As-You-Go-Nonprod'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       az aks get-credentials --resource-group mydemorg1 --name raviakscluster

- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'ravikubeconnection'
    namespace: 'default'
    manifests: 'aks-store-quickstart.yaml'

